//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGSDeveloperTest.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int UniqueId { get; set; }
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CompletedByDateTime { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
